In [7]:
import z2_helpers
import numpy as np

In [17]:
x = np.random.randint(0,2,size=(4,4))
y = z2_helpers.z2lin.kernel(x)
print(x,y)

[[1 1 0 0]
 [0 1 0 1]
 [0 0 0 0]
 [0 1 0 1]] [[0 1]
 [0 1]
 [1 0]
 [0 1]]
